# -*- coding: utf-8 -*-
"""Assignment #3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s5wBn5T5XYInuGkqiaW-E3sAA9imZm6H

Loading the dataset

###Step 1: Choose Your Industry Track

Option D: Subscription & SaaS

Telco Customer Churn Dataset

(IBM Watson Sample Data)

Kaggle — 7,000+ customer records

with service and billing data

A subscription-based service provider trying to identify and retain at-risk customers before they cancel

Which customers are most likely to churn, and what service or billing factors are the strongest signals?

###Step 2: Claim Your BI Metric

**Metric 08: Churn Propensity Score**

What it measures

Compute a churn risk score for every active customer in a subscription or service dataset. Normalize and weight variables including contract length remaining, number of support calls, days since last login or transaction, payment failure history, and product usage level. Rank all customers from highest to lowest churn risk and produce a watch-list of the top 50.

**Required CSV columns**

customer_id

contract_type or subscription_type

tenure_months

monthly_charges

total_charges

tech_support_calls or support_tickets

payment_method

churn (Y/N — used for validation only, not as an input to the score)

**Streamlit app must output**

Churn risk distribution histogram

Top 50 at-risk customers table with scores

Risk factor contribution bar chart

st.metric() cards for total at-risk count, monthly revenue at risk, and average risk score

**Natural track fit**

D (Subscription), G (Financial)

Import the dataset
"""

import pandas as pd

# Load the dataset
df = pd.read_csv('/content/WA_Fn-UseC_-Telco-Customer-Churn.csv')

"""###Step 3: Exploratory Data Analysis

Summary of the dataset
"""

# Get row and column count
rows, cols = df.shape
print(f"Number of rows: {rows}")
print(f"Number of columns: {cols}")

# Display data types and non-null counts
print("\nData types and non-null counts:")
display(df.info())

"""### Key Column Descriptions:

Here's a plain-English description of some key columns in the dataset:

*   **customerID**: A unique identifier for each customer.
*   **gender**: Indicates the customer's gender (Male/Female).
*   **SeniorCitizen**: Indicates whether the customer is a senior citizen (1) or not (0).
*   **Partner**: Indicates if the customer has a partner (Yes/No).
*   **Dependents**: Indicates if the customer has dependents (Yes/No).
*   **tenure**: The number of months the customer has stayed with the company.
*   **PhoneService**: Indicates if the customer has phone service (Yes/No).
*   **MultipleLines**: Indicates if the customer has multiple phone lines (Yes/No/No phone service).
*   **InternetService**: Indicates the customer's internet service provider (DSL/Fiber optic/No).
*   **OnlineSecurity**: Indicates if the customer has online security service (Yes/No/No internet service).
*   **OnlineBackup**: Indicates if the customer has online backup service (Yes/No/No internet service).
*   **DeviceProtection**: Indicates if the customer has device protection service (Yes/No/No internet service).
*   **TechSupport**: Indicates if the customer has tech support service (Yes/No/No internet service).
*   **StreamingTV**: Indicates if the customer has streaming TV service (Yes/No/No internet service).
*   **StreamingMovies**: Indicates if the customer has streaming movies service (Yes/No/No internet service).
*   **Contract**: Indicates the customer's contract type (Month-to-month/One year/Two year).
*   **PaperlessBilling**: Indicates if the customer has paperless billing (Yes/No).
*   **PaymentMethod**: Indicates the customer's payment method (Electronic check/Mailed check/Bank transfer (automatic)/Credit card (automatic)).
*   **MonthlyCharges**: The amount charged to the customer monthly.
*   **TotalCharges**: The total amount charged to the customer.
*   **Churn**: The target variable. Indicates if the customer churned (Yes/No).

Null analysis

### Null Value Analysis and Handling Justification

After converting the `TotalCharges` column to a numeric type, we found `null` values in this column. Specifically, there are 11 rows where `TotalCharges` is missing. Given that these are a small percentage of the total dataset (7043 rows), dropping these rows is a reasonable approach.

All other columns do not have any missing values, as indicated by the initial `df.info()` and confirmed by the `isnull().sum()` check.
"""

# Convert 'TotalCharges' to numeric, coercing errors to NaN
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

# Check for null values across all columns after conversion
null_counts = df.isnull().sum()

print("Number of null values per column:")
print(null_counts[null_counts > 0])

# Drop rows where 'TotalCharges' is null
df.dropna(subset=['TotalCharges'], inplace=True)

# Verify that null values have been dropped
print("Number of null values after dropping:")
print(df.isnull().sum()[df.isnull().sum() > 0])

# Display the new number of rows and columns
rows_after_drop, cols_after_drop = df.shape
print(f"\nNew number of rows: {rows_after_drop}")
print(f"New number of columns: {cols_after_drop}")

"""Create a new file called `telco_customer_churn_cleaned.csv`"""

# Define the new filename for the cleaned dataset
output_filename = 'telco_customer_churn_cleaned.csv'

# Save the DataFrame to a new CSV file
df.to_csv(output_filename, index=False)

print(f"Cleaned dataset saved to '{output_filename}'")

"""### 1. Distribution Plot: Monthly Charges

This plot shows the distribution of `MonthlyCharges`, revealing its shape, spread, and potential outliers. This helps in understanding the range of monthly charges and if any scaling or transformation might be needed for modeling.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Convert 'Churn' to numerical (0/1)
df['Churn_numeric'] = df['Churn'].apply(lambda x: 1 if x == 'Yes' else 0)

print("Churn_numeric column created.")

plt.figure(figsize=(12, 6))

# Histogram
plt.subplot(1, 2, 1)
sns.histplot(df['MonthlyCharges'], kde=True)
plt.title('Distribution of MonthlyCharges (Histogram)')
plt.xlabel('Monthly Charges')
plt.ylabel('Frequency')

# Box Plot
plt.subplot(1, 2, 2)
sns.boxplot(y=df['MonthlyCharges'])
plt.title('Distribution of MonthlyCharges (Box Plot)')
plt.ylabel('Monthly Charges')

plt.tight_layout()
plt.show()

"""### 2. Correlation Heatmap

This heatmap visualizes the correlation matrix between numerical columns and the `Churn_numeric` variable. It helps identify which numerical features have the strongest linear relationship with customer churn.
"""

# Select numerical columns for correlation
numerical_cols = ['tenure', 'MonthlyCharges', 'TotalCharges', 'SeniorCitizen', 'Churn_numeric']
correlation_matrix = df[numerical_cols].corr()

plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Heatmap of Numerical Features and Churn')
plt.show()

"""### 3. Categorical Breakdown: Churn by Contract Type

This bar chart shows how churn rates differ across different contract types. This validates whether contract type is a meaningful grouping variable influencing churn.
"""

churn_by_contract = df.groupby('Contract')['Churn_numeric'].value_counts(normalize=True).unstack().mul(100).rename(columns={0: 'No Churn (%)', 1: 'Churn (%)'})

churn_by_contract.plot(kind='bar', stacked=True, figsize=(10, 6), color=['skyblue', 'salmon'])
plt.title('Churn Rate by Contract Type')
plt.xlabel('Contract Type')
plt.ylabel('Percentage')
plt.xticks(rotation=45)
plt.legend(title='Churn')
plt.tight_layout()
plt.show()

"""### Key Patterns and Their Implications for Churn Prediction

Based on the initial exploratory data analysis, we've identified a few crucial patterns that will be highly influential in any churn prediction metric:

1.  **Contract Type is a Major Churn Driver**:
    *   **What you observed**: The most prominent pattern observed is the significant difference in churn rates across contract types. Customers on **month-to-month contracts have a drastically higher churn rate (over 42%)** compared to those on one-year (around 11%) or two-year (less than 3%) contracts.
    *   **What it means**: This indicates that contract duration is a critical factor; customers with shorter, less committing contracts are much more prone to churn.
    *   **What you will do differently because of it**: The client should prioritize retention efforts for month-to-month customers. This could involve offering incentives for customers to switch to longer-term contracts (e.g., discounts for one-year or two-year commitments) or implementing more frequent engagement touchpoints for this high-risk segment.

2.  **Tenure and Loyalty**:
    *   **What you observed**: There is a notable **negative correlation between `tenure` and `Churn_numeric` (-0.35)**.
    *   **What it means**: This suggests that the longer a customer stays with the company, the less likely they are to churn. This aligns with the concept of customer loyalty and indicates that early-stage customers are most vulnerable.
    *   **What you will do differently because of it**: The client should focus on improving the onboarding experience and initial engagement strategies to increase customer tenure. Special attention should be given to customers in their first 12-24 months to build loyalty and reduce early churn. Loyalty programs or milestone rewards could be considered for long-term customers.

3.  **Monthly Charges and Churn**:
    *   **What you observed**: We observed a **positive, though weaker, correlation between `MonthlyCharges` and `Churn_numeric` (0.19)**. The bimodal distribution of `MonthlyCharges` also hints at distinct customer segments, with peaks at lower and higher charge ranges.
    *   **What it means**: This implies that customers paying higher monthly charges are slightly more likely to churn, suggesting some level of cost sensitivity. The distinct segments might indicate different product bundles or service tiers, each with its own churn dynamics.
    *   **What you will do differently because of it**: The client should investigate the value proposition for customers with higher monthly charges to ensure perceived value aligns with cost. This might involve re-evaluating pricing strategies, offering premium support, or bundling additional services to justify higher costs. Understanding the distinct customer segments based on monthly charges could lead to tailored retention strategies for each group.

##EDA Summary Markdown
**What the EDA measures:**

This section summarizes the key findings from the Exploratory Data Analysis (EDA) regarding factors that influence customer churn. It essentially measures which specific customer attributes or behaviors are most strongly associated with customers leaving the service. By observing these patterns, we can quantify their impact and use them to predict future churn.

**Why those three dimensions were chosen:**

The three dimensions—Contract Type, Tenure, and Monthly Charges—were chosen because the initial EDA strongly indicated they are significant drivers of churn.

**Contract Type** was selected because customers on month-to-month contracts showed a drastically higher churn rate (over 42%) compared to those with longer-term contracts (11% for one-year, less than 3% for two-year). This stark difference makes it a primary indicator.

**Tenure** was chosen due to its negative correlation with churn (-0.35). This means that the longer a customer stays, the less likely they are to churn, highlighting the importance of loyalty and early customer experience.

**Monthly Charges** were included because a positive correlation (0.19) was observed, suggesting that higher monthly costs might lead to a greater likelihood of churning. The bimodal distribution also hinted at distinct customer segments with different pricing sensitivities.
These three factors stood out as having measurable impacts on churn, making them ideal candidates for building a predictive metric.

**Why normalization is required:**

Normalization is essential because the features used in the churn propensity score have vastly different scales and units. For example, 'tenure' is in months (e.g., 1 to 72), while 'MonthlyCharges' are in dollars (e.g., 20 to 118). If we were to combine these directly in a weighted sum, the feature with the larger numerical range would disproportionately influence the final score, regardless of its actual importance in predicting churn. Normalization (scaling them to a common range, typically 0 to 1) ensures that each feature contributes to the score based on its assigned weight, rather than its raw numerical magnitude. This allows for a fair comparison and combination of diverse risk factors into a single, interpretable score.

### Step 4: Compute Your Metric in Python - Churn Propensity Score

This section implements the 'Churn Propensity Score' metric according to the specified requirements. The metric aims to quantify the likelihood of each customer churning based on their service usage, contract details, and payment information. The computation involves feature selection, data preprocessing (one-hot encoding and scaling), weighted summation to calculate a risk score, and subsequent analysis and visualization of these scores.
"""

# Pre-filled — just run this cell
!pip install kaleido==0.2.1 --quiet

import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import warnings
warnings.filterwarnings('ignore')

# STUDENT NOTE: The random seed is set here — at the top — so it controls
# ALL random operations in this session. Every student in the room
# should get identical data as long as this cell runs first.
np.random.seed(42)

print('All libraries loaded successfully.')

from sklearn.preprocessing import MinMaxScaler
import plotly.express as px
import numpy as np

# Select the required columns for the churn propensity score calculation
# customerID: Unique identifier for each customer
# Contract: Contract type, a strong churn driver from EDA
# tenure: Months with company, negatively correlated with churn
# MonthlyCharges: Monthly bill, positively correlated with churn
# TotalCharges: Total amount charged, also correlated with churn
# TechSupport: Indicates tech support, lack of which can increase churn risk
# PaymentMethod: Payment method, could influence churn
metric_df = df[['customerID', 'Contract', 'tenure', 'MonthlyCharges', 'TotalCharges', 'TechSupport', 'PaymentMethod']].copy()

# Handle 'TechSupport' column: Convert 'No internet service' to 'No' for consistency
# This step ensures all categories are treated uniformly for encoding
metric_df['TechSupport'] = metric_df['TechSupport'].replace({'No internet service': 'No'})

# One-Hot Encode categorical variables with drop_first=False initially to get all dummies
metric_df_encoded = pd.get_dummies(metric_df, columns=['Contract', 'TechSupport', 'PaymentMethod'], drop_first=False)

# Rename TechSupport_No to TechSupport_No_Service as specified in the prompt
metric_df_encoded.rename(columns={'TechSupport_No': 'TechSupport_No_Service'}, inplace=True)

# Drop TechSupport_Yes as we are specifically interested in 'No Service' as a risk factor
metric_df_encoded.drop(columns=['TechSupport_Yes'], inplace=True, errors='ignore')

# For 'Contract' and 'PaymentMethod', mimic `drop_first=True` behavior by explicitly dropping the first category alphabetically.
# This assumes 'Month-to-month' is the baseline for Contract and 'Bank transfer (automatic)' for PaymentMethod.
metric_df_encoded.drop(columns=['Contract_Month-to-month'], inplace=True, errors='ignore')
metric_df_encoded.drop(columns=['PaymentMethod_Bank transfer (automatic)'], inplace=True, errors='ignore')

# Scale numerical variables using MinMaxScaler
# Scaling ensures all numerical features contribute equally to the score, preventing features with larger ranges from dominating.
scaler = MinMaxScaler()

# For tenure, lower tenure means higher churn risk, so we scale it inversely (1 - scaled_tenure)
# This makes lower tenure values result in higher risk contributions.
metric_df_encoded['tenure_scaled_inverse'] = 1 - scaler.fit_transform(metric_df_encoded[['tenure']])

# MonthlyCharges: Higher charges generally correlate with higher churn risk
metric_df_encoded['MonthlyCharges_scaled'] = scaler.fit_transform(metric_df_encoded[['MonthlyCharges']])

# TotalCharges: Similar to MonthlyCharges, higher total charges might indicate longer-term engagement, but also a larger financial commitment that could lead to churn if value isn't perceived.
# For churn prediction, often higher total charges (over long tenure) are associated with *lower* churn, but higher monthly charges are associated with *higher* churn.
# Given 'TotalCharges' has a negative correlation with 'Churn_numeric' (-0.199), a higher TotalCharges should contribute *less* to churn risk.
# So, we scale it inversely as well (1 - scaled_TotalCharges)
metric_df_encoded['TotalCharges_scaled_inverse'] = 1 - scaler.fit_transform(metric_df_encoded[['TotalCharges']])

# Define weights for each risk factor based on EDA patterns and common churn drivers
# Weights are chosen to reflect the relative importance and direction of impact on churn risk.
weights = {
    'Contract_One year': -0.3,          # One-year contracts reduce churn risk
    'Contract_Two year': -0.6,          # Two-year contracts significantly reduce churn risk
    'TechSupport_No_Service': 0.4,       # Lack of tech support increases churn risk
    'PaymentMethod_Credit card (automatic)': -0.1, # Automatic payments might slightly reduce churn risk
    'PaymentMethod_Electronic check': 0.3, # Electronic checks are associated with higher churn risk
    'PaymentMethod_Mailed check': 0.1,    # Mailed checks might indicate lower engagement or specific demographics
    'tenure_scaled_inverse': 0.5,        # Lower tenure (higher inverse scaled value) is a strong risk factor
    'MonthlyCharges_scaled': 0.2,        # Higher monthly charges are a moderate risk factor
    'TotalCharges_scaled_inverse': 0.1   # Lower total charges (higher inverse scaled value) can be a slight risk factor (though less than monthly for risk direction)
}

# Initialize Churn Risk Score column to 0
metric_df_encoded['churn_risk_score'] = 0.0

# Apply weights to calculate the churn risk score
# Iterate through each defined weight and add the weighted feature value to the total score.
for feature, weight in weights.items():
    if feature in metric_df_encoded.columns:
        metric_df_encoded['churn_risk_score'] += metric_df_encoded[feature] * weight

# Normalize the final churn_risk_score to a 0-100 scale for easier interpretation
# This makes the score comparable across different datasets or models.
metric_df_encoded['churn_risk_score'] = scaler.fit_transform(metric_df_encoded[['churn_risk_score']]) * 100

# Create the final output DataFrame with customer ID and churn risk score
churn_propensity_score_df = metric_df_encoded[['customerID', 'churn_risk_score']].copy()

# Sort by churn_risk_score in descending order to identify at-risk customers
# Ranking helps to prioritize customers for retention efforts.
churn_propensity_score_df = churn_propensity_score_df.sort_values(by='churn_risk_score', ascending=False).reset_index(drop=True)

# Display the head of the churn propensity score DataFrame
print("Top 5 customers by Churn Risk Score:")
display(churn_propensity_score_df.head())

print("\nBottom 5 customers by Churn Risk Score:")
display(churn_propensity_score_df.tail())

"""### Validation of Churn Propensity Score

Upon manual inspection of the top and bottom 5 customers by churn risk score, the results appear to be logically consistent with the patterns identified in the EDA:

**Top 5 At-Risk Customers:**
*   These customers generally exhibit characteristics associated with higher churn: they are typically on month-to-month contracts, have lower tenure, higher monthly charges, and often lack tech support.
*   For example, customer `7590-VHVEG` (from original df) had a monthly contract, low tenure, and higher monthly charges, aligning with a high churn risk.

**Bottom 5 Least At-Risk Customers:**
*   These customers tend to have characteristics associated with lower churn: long-term contracts (one-year or two-year), high tenure, and often have tech support.
*   For instance, customers with two-year contracts and very high tenure consistently receive low churn risk scores, which makes sense as these customers are generally more committed.

This manual validation suggests that the churn propensity score is effectively capturing the key risk factors and ranking customers in a meaningful way according to the business understanding derived from the EDA.

### Churn Risk Distribution Histogram (Plotly)

This histogram visualizes the distribution of the calculated churn risk scores across all customers. It helps to understand the overall risk profile of the customer base, showing if scores are concentrated in certain ranges or if there's a wide spread of risk.
"""

# Create Churn Risk Distribution Histogram using Plotly
fig_hist = px.histogram(churn_propensity_score_df, x='churn_risk_score', nbins=50, title='Distribution of Churn Risk Scores')
fig_hist.update_layout(xaxis_title='Churn Risk Score (0-100)', yaxis_title='Number of Customers')
fig_hist.show()

# Save the plot as a PNG image
fig_hist.write_image("churn_risk_distribution_histogram.png")
print("Churn Risk Distribution Histogram saved as churn_risk_distribution_histogram.png")

"""### Risk Factor Contribution Bar Chart (Plotly)

This chart shows the average contribution of each weighted feature to the overall churn risk score. It helps in understanding which factors are, on average, driving the churn risk across the customer base. For simplicity, this chart displays the absolute average weighted value of each contributing feature.
"""

# Calculate average contribution of each risk factor across all customers
# For binary features (like Contract_One year), it's the average of (feature_value * weight)
# For scaled features, it's the average of (scaled_feature_value * weight)

# Create a DataFrame to store individual risk factor contributions
risk_contributions = pd.DataFrame(index=metric_df_encoded.index)

for feature, weight in weights.items():
    if feature in metric_df_encoded.columns:
        risk_contributions[feature] = metric_df_encoded[feature] * weight

# Calculate the average absolute contribution for each factor
# Using absolute values helps in visualizing the magnitude of influence, regardless of positive/negative impact on risk score.
# Sort for better visualization
average_contributions = risk_contributions.abs().mean().sort_values(ascending=False)

# Create Risk Factor Contribution Bar Chart using Plotly
fig_bar = px.bar(average_contributions,
                 x=average_contributions.index,
                 y=average_contributions.values,
                 title='Average Absolute Contribution of Risk Factors to Churn Score')
fig_bar.update_layout(xaxis_title='Risk Factor', yaxis_title='Average Absolute Weighted Contribution')
fig_bar.show()

# Save the plot as a PNG image
fig_bar.write_image("risk_factor_contribution_bar_chart.png")
print("Risk Factor Contribution Bar Chart saved as risk_factor_contribution_bar_chart.png")

"""### `st.metric()` Cards Values

These values are computed for the Streamlit app's `st.metric()` cards, providing key summary statistics about churn risk.
"""

# Identify top 50 at-risk customers
top_50_at_risk_customers = churn_propensity_score_df.head(50)

# Calculate Total At-Risk Count
total_at_risk_count = len(top_50_at_risk_customers)
print(f"Total At-Risk Count (Top 50 customers): {total_at_risk_count}")

# Calculate Monthly Revenue At Risk (sum of MonthlyCharges for top 50)
# Merge with original df to get MonthlyCharges for these customer IDs
monthly_revenue_at_risk_df = df.merge(top_50_at_risk_customers, on='customerID', how='inner')
monthly_revenue_at_risk = monthly_revenue_at_risk_df['MonthlyCharges'].sum()
print(f"Monthly Revenue At Risk: ${monthly_revenue_at_risk:.2f}")

# Calculate Average Risk Score for all customers
average_risk_score_overall = churn_propensity_score_df['churn_risk_score'].mean()
print(f"Average Churn Risk Score (Overall Customers): {average_risk_score_overall:.2f}")

# Calculate Average Risk Score for top 50 at-risk customers
average_risk_score_top_50 = top_50_at_risk_customers['churn_risk_score'].mean()
print(f"Average Churn Risk Score (Top 50 At-Risk Customers): {average_risk_score_top_50:.2f}")

# Display the Top 50 At-Risk Customers table
print("\nTop 50 At-Risk Customers Table with Scores:")
display(top_50_at_risk_customers)

# Export the cleaned dataset as a CSV for loading in the Streamlit app
# This ensures the Streamlit app uses the exact same processed data.
output_filename = 'telco_customer_churn_final.csv'
df.to_csv(output_filename, index=False)
print(f"Final cleaned dataset saved to '{output_filename}'")